### ISSUE TITLE
Issue in /src/pages/guides/getting-started/create-event-integration.md

### ISSUE THREAD

**Issue by robrat** [AdobeDocs/cloudmanager-api-docs#264]
### Expected Behaviour

Creating a project with Cloud Manager as event is possible.

### Actual Behaviour

Cloud Manager isn't available as Event (tested by me with Developer role as well by a colleague with System Administrator role)

It is also not possible to edit any already existing Cloud Manager events. A layer named "Configure event registration" opens with a spinner, but it is spinning forever and no content becomes visible. In parallel, a javascript error is logged to the console:

```text
EventsWizard.js:440 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
    at EventsWizard.js:440:113
    at Array.map (<anonymous>)
    at EventsWizard.js:431:57
    at Array.reduce (<anonymous>)
    at u.<anonymous> (EventsWizard.js:426:63)
    at f (runtime.js:63:1)
    at Generator._invoke (runtime.js:293:1)
    at Generator.next (runtime.js:118:1)
    at R (EventsWizard.js:661:16)
    at a (EventsWizard.js:661:16)
```

#### Steps to Reproduce

Follow the steps written at https://developer.adobe.com/experience-cloud/cloud-manager/guides/getting-started/create-event-integration/ or edit an event at https://developer.adobe.com/console/projects/109715/4566206088344550768/events/168243/details

#### Platform and Version

Google Chrome Version 114.0.5735.198 (Official Build) (64-bit) (Linux)

#### Sample Code that illustrates the problem

n/a

#### Logs taken while reproducing problem

```text
EventsWizard.js:440 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
    at EventsWizard.js:440:113
    at Array.map (<anonymous>)
    at EventsWizard.js:431:57
    at Array.reduce (<anonymous>)
    at u.<anonymous> (EventsWizard.js:426:63)
    at f (runtime.js:63:1)
    at Generator._invoke (runtime.js:293:1)
    at Generator.next (runtime.js:118:1)
    at R (EventsWizard.js:661:16)
    at a (EventsWizard.js:661:16)
```

**Comment by robrat** [comment]
Was solved via bugfix release by IO engineering.
